Repository spiral/validator, pull requests merged in 2022-09, with the labels that each got.

#4 ArrayChecker::of checker can be array
  src/Checker/ArrayChecker.php
  tests/src/Unit/Checkers/ArrayTest.php
Labels: bug

#5 Adding default validator
  composer.json
  src/Bootloader/ValidatorBootloader.php
  tests/src/Functional/Bootloader/ValidatorBootloaderTest.php
Labels: enhancement

#6 Updating readme, updating CI
  .github/workflows/phpunit.yml
  .github/workflows/run-tests.yml
  .github/workflows/static-analysis.yml
  README.md
Labels: documentation
